services:
 frontend:
   public: true
   image: okteto/frontend:latest
   build: frontend/Dockerfile
   ports:
     - 80
 
 api:
   image: okteto/api:latest
   build: api/Dockerfile
   replicas: 2
   ports:
     - 8080
 
 worker:
   image: okteto/api:latest
   build: api/Dockerfile
   command: ./run_celery.sh
 
 db:
   image: postgres:9.4
   environment:
     - POSTGRES_PASSWORD=$PASSWORD
     - POSTGRES_DB=postgres
   ports:
     - 5432
   volumes:
     - /data
 
 cache:
   image: redis:2.8.19
   ports:
     - 6379