{{- range $name, $service := .Values.services }}
{{ if $service.ports }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $name }}"
  labels:
    dev.okteto.com/mola: "{{ $name }}"
    app.kubernetes.io/component: "{{ $name }}"
    app.kubernetes.io/instance: "test"
  {{ if $service.public }}annotations:
    dev.okteto.com/auto-ingress: "true"{{ end }}
spec:
  type: ClusterIP
  ports:
  {{- range $port := $service.ports }}
  - port: {{ $port }}{{ end }}
  selector:
    dev.okteto.com/mola: "{{ $name }}"
---
{{- end }}
{{- end }}
